site_name: 'SurfersLookout RESTful Service'
repo_url: https://github.com/surfersreport/surfers-api
repo_name: Github
edit_uri: blob/main/docs/
docs_dir: docs
nav:
  - Home: index.md
  - Tasks: tasks.md
  - Bugs: bugs.md
plugins:
  - techdocs-core
